# Generated by Django 5.2 on 2025-05-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('cif', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
                ('movil', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('customer_type', models.CharField(choices=[('D', 'DOMESTICO'), ('P', 'PYME'), ('A', 'AUTONOMO'), ('I', 'INDUSTRIAL')], max_length=50)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('codigo_postal', models.CharField(max_length=5, null=True)),
                ('poblacion', models.CharField(max_length=50, null=True)),
                ('municipio', models.CharField(max_length=50, null=True)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
