# Generated by Django 5.0.7 on 2025-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=4)),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
